### PR TITLE
adding new contacts page and more pictures to images folder

### PR DESCRIPTION
**Pull request by ighellache**

### CODE REVIEW

**Comment by ighellache** [comment]
I will add the meet the team section to index.html file tomorrow

**Comment by LL835** [comment]
Hey, is there maybe supposed to be a contact.html file included here?

**Comment by ighellache** [comment]
Yes, not sure why it didn't add it in. I'm adding it again, thanks for letting me know.

**Comment by ighellache** [comment]
Okay, I've created another pull request. Also, the branch is saying there are conflicts because I created a temporary logo and commented out some of the navbar options - should be easy to resolve - do have a look first though - thank you

**Review by LL835 — APPROVED** [review]

**Pull request merged**
